package:
  name: fedfred
  version: 2.0.9

source:
  url: "https://pypi.io/packages/source/f/fedfred/fedfred-2.0.9.tar.gz"
  sha256: "4e79f2ed61dbc73ef25d1be04872d5224fde8a3f870babf6c7c34f31d83508be"

build:
  noarch: python
  number: 0
  script: |
    python -m pip install . -vv

requirements:
  host:
    - python >=3.9,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.9,<4.0
    - httpx
    - tenacity
    - pandas
    - geopandas
    - conda-forge::polars
    - conda-forge::cachetools
    - conda-forge::asyncache
    - conda-forge::dask
    - conda-forge::dask-geopandas

test:
  imports:
    - fedfred
  requires:
    - pip
  commands:
    - pip check

about:
  home: "https://github.com/nikhilxsunder/fedfred"
  doc_url: "https://pypi.io/packages/source/f/fedfred/fedfred-2.0.9.tar.gz"
  dev_url: "https://pypi.io/packages/source/f/fedfred/fedfred-2.0.9.tar.gz"
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  summary: "A feature-rich python package for interacting with the Federal Reserve Bank of St. Louis Economic Database (FRED)"
  description: |
    FedFred is a Python package for interacting with the Federal Reserve Bank of St. Louis Economic Database (FRED API).
    It provides a feature-rich interface with:
    - Pandas/Polars DataFrame outputs
    - Native support for asynchronous requests
    - Local caching for faster execution
    - GeoPandas outputs for geographical data (FRED-Maps/GeoFRED)
    - MyPy compatible type stubs

extra:
  recipe-maintainers:
    - nikhilxsunder
